defaults:
  - experiment: normal  # Default mode
  - _self_

seed: 42
epochs: 10
lr: 0.01
batch_size: 16

loss:
  name: MSELoss
  params: {}

model:
  _target_: build_model.SimpleMNISTNet
  hidden_dim: 128

optimizer:
  _target_: torch.optim.SGD
  lr: ${lr}

hydra:
  job:
    chdir: False